# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gk7pmtDMfpiDRXfmMMonMBYk-FanUL2I
"""

import pandas as pd
import numpy as np
from prophet import Prophet

data = pd.read_csv("https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_train.csv")

data["Timestamp"] = pd.to_datetime(data["Timestamp"])

data["trips"] = pd.to_numeric(data["trips"], errors = "coerce")

TT = data.loc[(data["Timestamp"].dt.year == data["year"].max()) & (data["Timestamp"].dt.month == 1), ["Timestamp", "trips"]]

TT = TT.rename(columns={"Timestamp": "ds", "trips": "y"})

model = Prophet(changepoint_prior_scale = 0.5, daily_seasonality = True)

modelFit = model.fit(TT)

future = model.make_future_dataframe(periods = 744, freq = "H")

forecast = modelFit.predict(future)

pred = pd.DataFrame(forecast[["ds", "yhat"]].tail(744))

pred.set_index("ds", inplace = True)

print(pred)