# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gk7pmtDMfpiDRXfmMMonMBYk-FanUL2I
"""

import pandas as pd
import numpy as np
from prophet import Prophet
import plotly.express as px

data = pd.read_csv("https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_train.csv")

TT = data[["Timestamp", "trips"]]

TT.Timestamp = pd.to_datetime(TT.Timestamp, infer_datetime_format=True)

TT = pd.DataFrame(TT.values, columns = ['ds', 'y'])

model = Prophet(changepoint_prior_scale=0.5, daily_seasonality=True)

modelFit = model.fit(TT)

future = model.make_future_dataframe(periods=365)

forecast = model.predict(future)

pred = model.plot_components(forecast)