# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gk7pmtDMfpiDRXfmMMonMBYk-FanUL2I
"""

import pandas as pd
import numpy as np
from prophet import Prophet

data = pd.read_csv("https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_train.csv")

TT = data.loc[data.month == 1,["Timestamp", "trips"]]

TT["Timestamp"] = pd.to_datetime(TT["Timestamp"])

TT["trips"] = pd.to_numeric(TT["trips"], errors = "coerce")

TT = pd.DataFrame(TT.values, columns = ["ds", "y"])

model = Prophet(changepoint_prior_scale = 0.5, daily_seasonality = True)

modelFit = model.fit(TT)

future = model.make_future_dataframe(periods = 744, freq = "h")

forecast = modelFit.predict(future)

pred = forecast[["ds", "yhat"]].tail(744).values

pred_values = pred[:, 1]

pred_values = np.array(pred_values, dtype = float)